import JSZip from "jszip";
import { jsPDF } from "jspdf";
import * as UTIF from "utif";
import { ProductionResult } from "./production-export";

export type ExportRecord={id:string;createdAt:string;method:string;format:string;fileName:string;size:number;sha256:string;widthMM:number;heightMM:number;warnings:number};

export async function createProductionPackage(result:ProductionResult){const zip=new JSZip(),primaryHash=await hashBlob(result.blob);zip.file(result.fileName,result.blob);const manifest={schemaVersion:1,createdAt:new Date().toISOString(),generator:"PrintStudio",method:result.method,dimensions:{widthMM:result.widthMM,heightMM:result.heightMM,pixelWidth:result.pixelWidth??null,pixelHeight:result.pixelHeight??null},primary:{fileName:result.fileName,mime:result.mime,size:result.blob.size,sha256:primaryHash},warnings:result.warnings};zip.file("manifest.json",JSON.stringify(manifest,null,2));zip.file("production-instructions.txt",instructions(result));return zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}})}

export async function createPDF(result:ProductionResult){const png=await rasterize(result),orientation=result.widthMM>result.heightMM?"landscape":"portrait",pdf=new jsPDF({orientation,unit:"mm",format:[result.widthMM,result.heightMM],compress:true});const bytes=new Uint8Array(await png.arrayBuffer());pdf.addImage(bytes,"PNG",0,0,result.widthMM,result.heightMM,undefined,"FAST");pdf.setProperties({title:result.fileName,subject:`${result.method} production artwork`,creator:"PrintStudio"});return pdf.output("blob")}

export async function createTIFF(result:ProductionResult){const png=await rasterize(result),bitmap=await createImageBitmap(png),canvas=document.createElement("canvas");canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("TIFF renderer unavailable");ctx.drawImage(bitmap,0,0);bitmap.close();const image=ctx.getImageData(0,0,canvas.width,canvas.height),encoded=UTIF.encodeImage(new Uint8Array(image.data.buffer),canvas.width,canvas.height,{t282:[300,1],t283:[300,1],t296:2});return new Blob([encoded],{type:"image/tiff"})}

export async function createGangSheet(result:ProductionResult,sheetWidthMM:number,sheetHeightMM:number,copies:number,gapMM=5){if(result.mime!=="image/png")throw new Error("Gang sheets require a rendered PNG source.");if(sheetWidthMM<=0||sheetHeightMM<=0||copies<1)throw new Error("Gang-sheet dimensions and copy count must be positive.");const dpi=300,w=Math.ceil(sheetWidthMM/25.4*dpi),h=Math.ceil(sheetHeightMM/25.4*dpi);if(w*h>36_000_000)throw new Error("Gang sheet exceeds the safe 36-megapixel browser limit; use the planned server rendering worker.");const source=await createImageBitmap(result.blob),tileW=result.widthMM/25.4*dpi,tileH=result.heightMM/25.4*dpi,gap=gapMM/25.4*dpi,cols=Math.max(1,Math.floor((w+gap)/(tileW+gap))),rows=Math.max(1,Math.floor((h+gap)/(tileH+gap)));if(cols*rows<copies){source.close();throw new Error(`Only ${cols*rows} copies fit at original size on this sheet.`)}const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");if(!ctx){source.close();throw new Error("Gang-sheet renderer unavailable")};for(let i=0;i<copies;i++){const col=i%cols,row=Math.floor(i/cols);ctx.drawImage(source,col*(tileW+gap),row*(tileH+gap),tileW,tileH)}source.close();return await canvasBlob(canvas,"image/png")}

export async function recordArtifact(result:ProductionResult,blob:Blob,fileName=result.fileName):Promise<ExportRecord>{const sha256=await hashBlob(blob),record:ExportRecord={id:crypto.randomUUID(),createdAt:new Date().toISOString(),method:result.method,format:blob.type||result.mime,fileName,size:blob.size,sha256,widthMM:result.widthMM,heightMM:result.heightMM,warnings:result.warnings.length};const db=await database();await transaction(db,"readwrite",store=>store.put({...record,blob}));return record}
export async function listArtifacts():Promise<ExportRecord[]>{const db=await database();const rows=await transaction<({blob:Blob}&ExportRecord)[]>(db,"readonly",store=>store.getAll());return rows.map(row=>({id:row.id,createdAt:row.createdAt,method:row.method,format:row.format,fileName:row.fileName,size:row.size,sha256:row.sha256,widthMM:row.widthMM,heightMM:row.heightMM,warnings:row.warnings})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export async function artifactBlob(id:string):Promise<{blob:Blob;fileName:string}|null>{const db=await database();const row=await transaction<({blob:Blob}&ExportRecord)|undefined>(db,"readonly",store=>store.get(id));return row?{blob:row.blob,fileName:row.fileName}:null}

async function rasterize(result:ProductionResult){if(result.mime==="image/png")return result.blob;const image=await loadImage(result.previewUrl),w=Math.ceil(result.widthMM/25.4*300),h=Math.ceil(result.heightMM/25.4*300);if(w*h>36_000_000)throw new Error("Raster conversion exceeds the safe browser limit.");const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Raster renderer unavailable");ctx.drawImage(image,0,0,w,h);return canvasBlob(canvas,"image/png")}
export const rasterizeArtifact=rasterize;
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("Preview could not be rasterized"));image.src=src})}
function canvasBlob(canvas:HTMLCanvasElement,type:string){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Image encoding failed")),type))}
async function hashBlob(blob:Blob){const digest=await crypto.subtle.digest("SHA-256",await blob.arrayBuffer());return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}
function instructions(r:ProductionResult){return [`PrintStudio production package`,`Method: ${r.method}`,`Physical size: ${r.widthMM} x ${r.heightMM} mm`,`Primary file: ${r.fileName}`,``,`Warnings:`,...(r.warnings.length?r.warnings.map(w=>`- ${w}`):["- None"]),``,`Verify device/RIP settings, material profile, colour handling and final dimensions before production.`].join("\r\n")}

const DB="printstudio-production",STORE="exports";
function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE,{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function transaction<T=void>(db:IDBDatabase,mode:IDBTransactionMode,action:(store:IDBObjectStore)=>IDBRequest){return new Promise<T>((resolve,reject)=>{const tx=db.transaction(STORE,mode),request=action(tx.objectStore(STORE));request.onsuccess=()=>resolve(request.result as T);request.onerror=()=>reject(request.error)})}
